name: CI avec Secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Utiliser un secret (de manière sécurisée)
      env:
        MON_SECRET_UTILISE_EN_INTERNE: ${{ secrets.M_SECRET }}
      run: |
        echo "Le script va utiliser le secret mais ne l'affichera PAS directement."
        if [ -n "$MON_SECRET_UTILISE_EN_INTERNE" ]; then
          echo "Le secret est bien passé en variable d'env !"
        else
          echo "Oops, le secret n'est pas là."
          exit 1
        fi
